### ISSUE TITLE
second version w2w

### ISSUE THREAD

**Issue by matthiasdemuzere** [matthiasdemuzere/wrf-lcz-KL#11] opened 2021-04-28 13:15 UTC
Hi @dargueso and @andreazonato,

I consider my second version of the tool ready.

All that was discussed in other Issue channels has been incorporated.
This new version now also includes HI_URB2D, which - if I understand well - would make the file ready for the other urban parameterizations.

I have added the outputs again in my [Google Drive folder (w2w_v2)](https://drive.google.com/drive/folders/15QsWRCxFEjZ7fo3C6iP9vqISPr5uw6l1?usp=sharing).

Please have a look. Let's hope this version is fine!

**Comment by dargueso** [comment] 2021-04-30 07:08
Hi,
I run the tool yesterday, inspected the output files and found them perfect. I couldn't spot any error or inconsistency in the files. Shall I move forward and start exp. B then? 
I can also start preparing exp C, I guess, but I need assistance from @andreazonato. Is there anything I need to do when preparing the boundary conditions or the changes are to be made only when running the model? 
Thanks

**Comment by andreazonato** [comment] 2021-04-30 07:16
Hi @dargueso,


You have to do nothing, WRF is able to do it by itself. The only thing I suggest you is to modify the Registry.EM_COMMON (or to give as output in the namelist) the following variables:

state    real   LP_URB2D       ij       misc      1        -     i0  "BUILD_AREA_FRACTION" "BUILDING PLAN AREA DENSITY"   "dimensionless"
state    real   HI_URB2D       i{uhi}j  misc      1        Z     i0  "HEIGHT_HISTOGRAMS" "DISTRIBUTION OF BUILDING HEIGHTS" "dimensionless"
state    real   LB_URB2D       ij       misc      1        -     i0  "BUILD_SURF_RATIO" "BUILDING SURFACE AREA TO PLAN AREA RATIO" "dimensionless"
state    real   HGT_URB2D      ij       misc      1        -     i0  "BUILD_HEIGHT" "AVERAGE BUILDING HEIGHT WEIGHTED BY BUILDING PLAN AREA" "m"
state    real   MH_URB2D       ij       misc      1        -     i0  "MH_URB2D"  "Mean Building Height" "m"
state    real   STDH_URB2D     ij       misc      1        -     i0  "STDH_URB2D" "Standard Deviation of Building Height" "m2"
state    real   LF_URB2D       i{udr}j  misc      1        Z     i0  "LF_URB2D"   "Frontal Area Index" "dimensionless"

adding the "h" in this way



state    real   LP_URB2D       ij       misc      1        -     ih0  "BUILD_AREA_FRACTION" "BUILDING PLAN AREA DENSITY"   "dimensionless"
state    real   HI_URB2D       i{uhi}j  misc      1        Z     ih0  "HEIGHT_HISTOGRAMS" "DISTRIBUTION OF BUILDING HEIGHTS" "dimensionless"
state    real   LB_URB2D       ij       misc      1        -     ih0  "BUILD_SURF_RATIO" "BUILDING SURFACE AREA TO PLAN AREA RATIO" "dimensionless"
state    real   HGT_URB2D      ij       misc      1        -     ih0  "BUILD_HEIGHT" "AVERAGE BUILDING HEIGHT WEIGHTED BY BUILDING PLAN AREA" "m"
state    real   MH_URB2D       ij       misc      1        -     ih0  "MH_URB2D"  "Mean Building Height" "m"
state    real   STDH_URB2D     ij       misc      1        -     ih0  "STDH_URB2D" "Standard Deviation of Building Height" "m2"
state    real   LF_URB2D       i{udr}j  misc      1        Z     ih0  "LF_URB2D"   "Frontal Area Index" "dimensionless"


so we are sure WRF reads them correctly.  Remember, for exp C) to add, in the &physics section of the namelist, the flag ##use_wudapt_lcz=1##. If you can show me the wrfinput_d02 of exp B) and C), I can say if it is gonna work or not.

**Comment by matthiasdemuzere** [comment] 2021-04-30 07:16
This is great news @dargueso. Thanks for checking. For me its fine to launch Exp. B, and start preparing for Exp. C.

The only thing I wanted to check perhaps are the values for the other urban parameters provided in URBPARM_LCZ.TBL.

@andreazonato: to be sure. Values that are already defined in URB_PARAM, will not be used from the look-up table, correct?

**Comment by andreazonato** [comment] 2021-04-30 07:21
> @andreazonato: to be sure. Values that are already defined in URB_PARAM, will not be used from the look-up table, correct?

That's correct!

**Comment by dargueso** [comment] 2021-04-30 10:11
Hi 
@andreazonato thanks for the indications, I will generate the inputs and let you know. I can send you the files for you to check. thanks!

@matthiasdemuzere I've been comparing your geo_em.d02_NoUrban.nc with mine and GREENFRAC is slightly different between them because in my case I didn't change GREENFRAC. This is not a problem, because GREENFRAC is homogenised in the urban areas anyway. I still think the current approach in the tool is fine, replacing GREENFRAC with the surrounding, just like the other variables. I just want to point it out, since for the NoUrban run I'm using the unchanged GREENFRAC file.

I'll keep you posted with advances

**Comment by dargueso** [comment] 2021-05-06 14:07
I bring the issue with the geo_em file here, since it is related to the w2w tool. I have solved the problem and it is related to the attributes of either GREENFRAC, LANDUSEF, LU_INDEX. I haven't tested them individually, but I think it is related to _FillValue taking a different value.

I have taken GREENFRAC, LANDUSEF and LU_INDEX values from your netCDF file (not the attributes) and rewritten to my geo_em file. I previously checked that those were the only three variables that differ in our files.

I can send you the file I created to make the WPS run. If you need it to see what should be fixed in the tool, let me know how should I send it. It's ~60M. Also. I don't understand why yours is ~160M and mine is ~60M. Probably the variable type also plays a role, but haven't checked.

I can work with my file, so no rush, but something needs fixing in the tool.

**Comment by matthiasdemuzere** [comment] 2021-05-06 14:35
Are you now talking about the input for Exp. B (*_LCZ_extent.nc) or Exp. C (*_LCZ_params.nc)?

For Exp. C, the file is much bigger as it includes the 3D URB_PARAM field, which contains a lot of additional urban parameters needed to run with the LCZ information. 

I would be surprised that the reason for not working is located in GREENFRAC, LANDUSEF and LU_INDEX?
The reason: The Exp. B file is created at the very end of w2w, by removing URB_PARAM from Exp. C file, and changing LU_INDEX. So if Exp. B runs, I am not sure why the error would be in those fields? 

Yet perhaps I am misunderstanding your comment above?

**Comment by dargueso** [comment] 2021-05-06 16:28
Ah! Ok. Now I see.

The problem is with Exp C. ( _LCZ_params.nc). I was checking differences in variables in both files, because I assumed at this stage those variables were the same. When I add the two new variables URB_FRC2D and URB_PARAM (the file size obviously matches yours) but I get a different error. My guess is that WPS -metgrid.exe for this purpose- is not expecting those variables. @andreazonato could that be the case? Do I need to modify METGRID.TBL to tell metrgrid.exe to read those two variables and, more importantly, how?

**Comment by andreazonato** [comment] 2021-05-07 07:51
@dargueso ,
First thing, the name of the variable is FRC_URB2D. Is it correct in @matthiasdemuzere 's code or not? I guess yes, you probably typed it wrong.

Anyway, I tnink the problem is not on the new two variables. Megrid takes all the variables in the geo_em, no matter the number of the kind of the variables. There can be some errors in the attributes. Could you please share the error with me?

**Comment by andreazonato** [comment] 2021-05-07 08:02
Some general observations, that can find the source of the problem:
![Screenshot (6)](https://user-images.githubusercontent.com/49075918/117417721-efac7780-af1a-11eb-8608-e3e5866151d6.png)
That's how the variable URB_PARAM should result inside the geo_em*, along with the flag FLAG_URB_PARAMS=1, as here:
![Screenshot (7)](https://user-images.githubusercontent.com/49075918/117417879-15d21780-af1b-11eb-98eb-d5f1a7e141b0.png)
@matthiasdemuzere 's code, instead, produces this:
![Screenshot (3)](https://user-images.githubusercontent.com/49075918/117417960-2c786e80-af1b-11eb-94c6-bb391cbb15aa.png)

Differences are in the "LL" whose appear in FieldType,sr_x and sr_y, that can be wrongly be read by the metgrid. Moreover, URB_PARAM is "double" instead of "float".

**Comment by matthiasdemuzere** [comment] 2021-05-07 08:47
Thanks for checking @andreazonato. So I basically have to check:

- Definition sr_x and sr_y? Seems to refer to wrong type of these variables
- include FLAG_URB_PARAMS=1 in the global attributes? This is something I did not know about, I will check.

Anything else?

**Comment by dargueso** [comment] 2021-05-07 08:50
Thanks @andreazonato 

Yes, FRC_URB2D is OK, I just mistyped it here.

@matthiasdemuzere, wait before implementing those changes, I'm currently modifying the files to see if that works of if anything else is needed.

It won't take long.

**Comment by matthiasdemuzere** [comment] 2021-05-07 08:53
Ok, thanks @dargueso. I'll wait ...

@andreazonato: I was looking for your example geo_em*.nc file which has the URB_PARAM fields etc, but I can not find it anymore? Is it on github? If not, could you send it again?

**Comment by andreazonato** [comment] 2021-05-07 09:04
I just updated the geo_em.d04.nc in the main directory here. @matthiasdemuzere, I think it is all what you need to add over there.
I had a look and actually metgrid reads sr_x and sr_y, so probably that's part of the issue. Moreover, FLAG_URB_PARAM is not used YET in the WRF code (just checked), but better to put it on the geo_em files.

**Comment by matthiasdemuzere** [comment] 2021-05-07 09:10
Ok, so that would reduce the issue to the data type of URB_PARAM? Let me know how you go @dargueso. If you get something working, I can implement the changes in the w2w tool ...

**Comment by dargueso** [comment] 2021-05-07 09:23
I've made a few changes, also I've set the num_land_cat was to 41 in the attributes. I've tried both with and without

                :FLAG_IMPERV = 1 ;
                :FLAG_CANFRA = 1 ;
                :FLAG_EROD = 1 ;
                :FLAG_CLAYFRAC = 1 ;
                :FLAG_SANDFRAC = 1 ;

but I still get an error when processing domain2 with metgrid.exe:

Processing domain 1 of 2
 Processing 2016-01-31_00
    ERA5
 Processing 2016-01-31_06
    ERA5
 Processing 2016-01-31_12
    ERA5
Processing domain 2 of 2
ERROR: In read_next_field(), got error code -1004.


Will continue looking for possible issues in the files

**Comment by dargueso** [comment] 2021-05-07 09:42
I don't know what else could be. I've tried a few things, but still get the same error. 
I just noticed that your sample file does not have the FRC_URB2D variable. I've removed it from our file, just to check but the error persists.
I will be keep trying to understand what the problem is, but if you have any ideas, more than happy to hear them.

**Comment by matthiasdemuzere** [comment] 2021-05-07 09:49
Mmmm ... I assume it is not possible to re-compile metgrid.exe after adding print statements to find out exactly where the code fails? The error you get does not seem to help us really?

**Comment by andreazonato** [comment] 2021-05-07 09:56
>ERROR: In read_next_field(), got error code -1004.

It is an issue with the URB_PARAM matrix, of course. It should be some of the attribute, or even the fact that it is double instead of float.

**Comment by matthiasdemuzere** [comment] 2021-05-07 10:18
@dargueso: could you try [this one](https://drive.google.com/file/d/10J6Fot35U66atI1wPHWseP8xB93AKAER/view?usp=sharing)? I just set URB_PARAM from float64 to float32, as in the example file of @andreazonato ....

**Comment by dargueso** [comment] 2021-05-07 10:21
I'm going to try that one. I just saw that Times is also different in the original/LCZ_extend and the LCZ_params files, so that may be causing problems too. Also the dimension land_cat should be changed to 41.  I'll try your file and if it doesn't work, I'll fix the issues with Times and dimensions.

**Comment by dargueso** [comment] 2021-05-07 10:24
Just saw the variable that use the land_cat dimension in @andreazonato'file. It is LANDUSEF and the attribute says "Noah-modified 41-category IGBP-MODIS landuse". It has LANDUSEF for each of the 41 categories. Ours has 21 for each of our 21 categories, with is the typical LANDUSEF without LCZs. Perhaps that could cause problems too. I'll see.

**Comment by matthiasdemuzere** [comment] 2021-05-07 10:28
I have been checking a few items as well, using @andreazonato his example file.

As you pointed out, the example file also has the following global attributes (which I do not have):
FLAG_SANDFRAC: 1
FLAG_IMPERV: 1
FLAG_CLAYFRAC: 1
FLAG_CANFRA: 1
FLAG_URB_PARAM: 1
FLAG_EROD: 1

Yet I would be surprised if these are causing the error?

I am surprised though that Times is different between LCZ_extend and LCZ_params? Since the former is a copy of the latter, but just removing some fields? See function [here](https://github.com/matthiasdemuzere/wrf-lcz-KL/blob/feb7b3ecd131f987dbfe3a181e92e66f4191051d/w2w.py#L766).

Just to be sure: you are using the files in the w2w_**v2** folder of my Google Drive, no?

**Comment by matthiasdemuzere** [comment] 2021-05-07 10:34
For clarity, see below all global attributes and their values for the example file (REF) and our new file (NEW).

Of course there are differences for all grid variables. Yet there are some others as well, for which I do not know whether they are important? Eg.:

**MAP_PROJ**: 
 REF: 1 
 NEW: 3

**NUM_LAND_CAT**: < -- already reported
 REF: 41 
 NEW: 21

ISLAKE: 
 REF: -1 
 NEW: 21

grid_id: 
 REF: 4 
 NEW: 2

parent_id: 
 REF: 3 
 NEW: 1

--- Full list ---

TITLE: 
 REF: OUTPUT FROM GEOGRID V4.1 
 NEW: OUTPUT FROM GEOGRID V4.2
SIMULATION_START_DATE: 
 REF: 0000-00-00_00:00:00 
 NEW: 0000-00-00_00:00:00
WEST-EAST_GRID_DIMENSION: 
 REF: 85 
 NEW: 331
SOUTH-NORTH_GRID_DIMENSION: 
 REF: 109 
 NEW: 321
BOTTOM-TOP_GRID_DIMENSION: 
 REF: 0 
 NEW: 0
WEST-EAST_PATCH_START_UNSTAG: 
 REF: 1 
 NEW: 1
WEST-EAST_PATCH_END_UNSTAG: 
 REF: 84 
 NEW: 330
WEST-EAST_PATCH_START_STAG: 
 REF: 1 
 NEW: 1
WEST-EAST_PATCH_END_STAG: 
 REF: 85 
 NEW: 331
SOUTH-NORTH_PATCH_START_UNSTAG: 
 REF: 1 
 NEW: 1
SOUTH-NORTH_PATCH_END_UNSTAG: 
 REF: 108 
 NEW: 320
SOUTH-NORTH_PATCH_START_STAG: 
 REF: 1 
 NEW: 1
SOUTH-NORTH_PATCH_END_STAG: 
 REF: 109 
 NEW: 321
GRIDTYPE: 
 REF: C 
 NEW: C
DX: 
 REF: 333.3333435058594 
 NEW: 1000.0
DY: 
 REF: 333.3333435058594 
 NEW: 1000.0
DYN_OPT: 
 REF: 2 
 NEW: 2
CEN_LAT: 
 REF: 46.083045959472656 
 NEW: 3.0050582885742188
CEN_LON: 
 REF: 11.144439697265625 
 NEW: 101.61739349365234
TRUELAT1: 
 REF: 46.06055450439453 
 NEW: 3.140000104904175
TRUELAT2: 
 REF: 46.06055450439453 
 NEW: 3.140000104904175
MOAD_CEN_LAT: 
 REF: 46.06055450439453 
 NEW: 3.1399917602539062
STAND_LON: 
 REF: 11.125 
 NEW: 104.5
POLE_LAT: 
 REF: 90.0 
 NEW: 90.0
POLE_LON: 
 REF: 0.0 
 NEW: 0.0
corner_lats: 
 REF: [45.92254  46.243343 46.243282 45.922474 45.92253  46.243343 46.243275
 45.922474 45.921036 46.244843 46.244778 45.920975 45.92103  46.244835
 46.244778 45.920975] 
 NEW: [1.5694427 4.438797  4.438797  1.5694427 1.5694427 4.438797  4.438797
 1.5694427 1.5649414 4.443283  4.443283  1.5649414 1.5649414 4.443283
 4.443283  1.5649414]
corner_lons: 
 REF: [10.965515 10.9646   11.324402 11.323242 10.963348 10.962433 11.326569
 11.325409 10.965515 10.964569 11.324402 11.323242 10.963379 10.962402
 11.326569 11.325409] 
 NEW: [100.13555  100.13555  103.099236 103.099236 100.13105  100.13105
 103.10374  103.10374  100.13555  100.13555  103.099236 103.099236
 100.13105  100.13105  103.10374  103.10374 ]
MAP_PROJ: 
 REF: 1 
 NEW: 3
MMINLU: 
 REF: MODIFIED_IGBP_MODIS_NOAH 
 NEW: MODIFIED_IGBP_MODIS_NOAH
NUM_LAND_CAT: 
 REF: 41 
 NEW: 21
ISWATER: 
 REF: 17 
 NEW: 17
ISLAKE: 
 REF: -1 
Traceback (most recent call last):
 NEW: 21
ISICE: 
  File "<input>", line 3, in <module>
 REF: 15 
KeyError: 'FLAG_URB_PARAM'
 NEW: 15
ISURBAN: 
 REF: 13 
 NEW: 13
ISOILWATER: 
 REF: 14 
 NEW: 14
grid_id: 
 REF: 4 
 NEW: 2
parent_id: 
 REF: 3 
 NEW: 1
i_parent_start: 
 REF: 38 
 NEW: 127
j_parent_start: 
 REF: 35 
 NEW: 133
i_parent_end: 
 REF: 65 
 NEW: 159
j_parent_end: 
 REF: 70 
 NEW: 164
parent_grid_ratio: 
 REF: 3 
 NEW: 10
sr_x: 
 REF: 1 
 NEW: 1
sr_y: 
 REF: 1 
 NEW: 1
FLAG_MF_XY: 
 REF: 1 
 NEW: 1

**Comment by dargueso** [comment] 2021-05-07 11:07
I'm using the latest version of your files, @matthiasdemuzere. Times variables are fine in your latest version, it looks like in the process of change some of the variables, "Times" was changed too. But still, after modifying all we've talked about, metgrid.exe crashes, albeit with a slightly different error. 

My guess now is that the error is related to num_cat_land, the dimension with that name and the size of landusef. If we tell metgrid that we're using 21 categories in the attributes and LANDUSEF variable, that should be consistent with the LU_INDEX values, and it is not. In fact, metgrid.exe crashes even without URB_PARAM in geo_em.d02.nc. Perhaps we should build LANDUSEF with 1-0 depending on the value of LU_INDEX? It is not straightforward for you with your existing scripts, I can do that after lunch.

**Comment by matthiasdemuzere** [comment] 2021-05-07 11:28
In [this file](https://drive.google.com/file/d/1cc4Z6hakINHg87yjwgVCvq5-rFTPlfsG/view?usp=sharing) I just changed NUM_CAT_LAND to 41, instead of 21.

**Comment by matthiasdemuzere** [comment] 2021-05-07 11:34
Related to LU_INDEX and LANDUSEF. 

LU_INDEX ranges from 1 to 41 (well 39 in our case, no LCZs 10 and 15).
LANDUSEF has only 21 dimensions: (1, **21**, 320, 330)

I checked in the example file:
There indeed LANDUSEF has 41 levels: (1, **41**, 108, 84)

So I guess I need to make LANDUSEF consistent with LU_INDEX, having 1's in LANDUSE_F that correspond to the LU_INDEX values. Let me also adjust this ...

**Comment by dargueso** [comment] 2021-05-07 11:36
Yep, I'm working on that already. Making LANDUSEF and LU_INDEX consistent.

**Comment by matthiasdemuzere** [comment] 2021-05-07 11:40
Ok!

**Comment by matthiasdemuzere** [comment] 2021-05-07 11:42
@andreazonato: I am confused again, so I just wanted to double check.

The LCZ classes in LU_INDEX are set as 30 to 40, or to 41?

Since 30 to (including) 41 are 12 classes, while there should only be 11 LCZ Classes (original names 1-10 and 15)?

**Comment by dargueso** [comment] 2021-05-07 12:29
Damn! Made it, it went through at least. I haven't checked much the results. 

FRC_URB2D must be removed. That was the main issue. metgrid.exe doesn't know how to interpret it. Not sure if because of the variable itself or because the lack of attributes. @andreazonato doesn't have that variable in it. Do we need it?

For it to work, a few other parameters must be adapted to make it consistent between LANDUSEF and LU_INDEX.

I haven't tested them one by one to see which one was the issue, I just tried to mimic @andreazonato file.

So @matthiasdemuzere from [this file](https://drive.google.com/file/d/10J6Fot35U66atI1wPHWseP8xB93AKAER/view?usp=sharing) I did the following (very dirty) in case you want to include it in the tool:

*I haven't tested the results, so some errors may have slipped in, but metgrid.exe likes it.

`ncks -x -v LANDUSEF geo_em.d02.nc aux.nc`

Then in python:

`import numpy as np
import netCDF4 as nc
fin_aux=nc.Dataset("aux.nc",mode='a')
fin_aux.createDimension('land_cat',41)
new_lusef=np.zeros((1,41,320,330),dtype=np.float)
for lu in range(41):
    new_lusef[0,lu,(fin_aux['LU_INDEX'][:]==(lu+1)).squeeze()]=1
outvar  = fin_aux.createVariable('LANDUSEF','f',('Time','land_cat','south_north','west_east'))
outvar[:]=new_lusef
setattr(outvar,'FieldType',104)
setattr(outvar,'MemoryOrder', "XYZ")
setattr(outvar,'units', "category")
setattr(outvar,'description', "Noah-modified 41-category IGBP-MODIS landuse")
setattr(outvar,'stagger', "M")
setattr(outvar,'sr_x', 1)
setattr(outvar,'sr_y', 1)

fin_aux.close()
`

Then back in bash using nco, some cleaning:

`cp aux.nc geo_em.d02.nc
ncatted -O -a sr_x,URB_PARAM,m,i,1 geo_em.d02.nc
ncatted -O -a sr_y,URB_PARAM,m,i,1 geo_em.d02.nc
ncatted -O -a FLAG_URB_PARAMS,global,m,i,1 geo_em.d02.nc
ncatted -h -a NUM_LAND_CAT,global,m,i,41 geo_em.d02.nc
ncatted -h -a NUM_LAND_CAT,global,m,i,41 geo_em.d02.nc
ncatted -O -a FieldType,LANDUSEF,m,i,104 geo_em.d02.nc
ncatted -O -a sr_x,LANDUSEF,m,i,1 geo_em.d02.nc
ncatted -O -a sr_y,LANDUSEF,m,i,1 geo_em.d02.nc
ncatted -h -a FLAG_URB_PARAM,global,c,i,1 geo_em.d02.nc
ncks -x -v FRC_URB2D geo_em.d02.nc aux.nc
cp aux.nc geo_em.d02.nc
ncatted -h -a NCO,global,d,c, geo_em.d02.nc
ncatted -h -a history,global,d,c, geo_em.d02.nc 
`

**Comment by matthiasdemuzere** [comment] 2021-05-07 12:38
Alright. Good step forward. Great.

Strange FRC_URB2D has to be removed. I remember @andreazonato stating this one is required? So let's see what he has to say about that. And in a way this is a critical variable, as this one decided the urban (and thus LCZ) fraction/coverage?

Also clarifying the exact LCZ LU_INDEX numbers (see earlier comment here) would be good.

Once that is clear, I can try to figure out all you have changed above, and mimic it in the tool as well.

**Comment by andreazonato** [comment] 2021-05-07 12:41
> @andreazonato: I am confused again, so I just wanted to double check.
> 
> The LCZ classes in LU_INDEX are set as 30 to 40, or to 41?
> 
> Since 30 to (including) 41 are 12 classes, while there should only be 11 LCZ Classes (original names 1-10 and 15)?
> 
> In the code, I now add 29 to the LCZ classes, see [here](https://github.com/matthiasdemuzere/wrf-lcz-KL/blob/feb7b3ecd131f987dbfe3a181e92e66f4191051d/w2w.py#L589).
> 
> Leading to:
> LCZ 1 -> 30
> LCZ 2 -> 31
> LCZ 3 -> 32
> LCZ 4 -> 33
> LCZ 5 -> 34
> LCZ 6 -> 35
> LCZ 7 -> 36
> LCZ 8 -> 37
> LCZ 9 -> 38
> LCZ 10 -> 39
> LCZ 11 (original LCZ 15) -> 40
> 
> But ... as you have LU_INDEX 41 in your file, I guess this is wrong? So I would need to do +30, so that
> LCZ 1 -> 31
> LCZ 2 -> 32
> ....


Yes, that's wrong! LCZ 1 start with number 31...until class 41 that is what I defined as asphalt! Moreover, regarding LANDUSEF and LU_INDEX, even if we have just up to LCZ=39,  num_land cat and the maximum number of LANDUSEF should be 411 (related to some lookup tables)

**Comment by andreazonato** [comment] 2021-05-07 12:42
float FRC_URB2D(Time, south_north, west_east) ;
                FRC_URB2D:FieldType = 104 ;
                FRC_URB2D:MemoryOrder = "XY " ;
                FRC_URB2D:units = "-" ;
                FRC_URB2D:description = "ufrac" ;
                FRC_URB2D:stagger = "M" ;
                FRC_URB2D:sr_x = 1 ;
                FRC_URB2D:sr_y = 1 ;



That's how attributes should be defined for FRC_URB2D... sorry I forgot to post them before!

**Comment by matthiasdemuzere** [comment] 2021-05-07 12:49
Ok, let me try to address all of the above. 

@dargueso: once I am done, I will let you know and then you can test this new file again?

**Comment by matthiasdemuzere** [comment] 2021-05-07 13:18
@andreazonato: for the Exp. B. file, where urban is denoted with LU_INDEX == 13, I assume NUM_LAND_CAT should be back to 21?

Any other attributes that need to be changed back? Eg. FLAG_URB_PARAM? Or something else?

**Comment by andreazonato** [comment] 2021-05-07 13:33
> @andreazonato: for the Exp. B. file, where urban is denoted with LU_INDEX == 13, I assume NUM_LAND_CAT should be back to 21?
> 
> Any other attributes that need to be changed back? Eg. FLAG_URB_PARAM? Or something else?


For Exp B), it does not matter NUM_LAND_CAT. Since LCZ are not read, it is the same. THE FLAG_URB_PARAM too, is not used by WRF. But probably better to put it in w2w.py, since FLAG_URB_PARAM can appear in the next releases.

**Comment by matthiasdemuzere** [comment] 2021-05-07 13:36
Ok if I set FLAG_URB_PARAM = 0 then? Or better remove?

Also, I assume LANDUSEF should have old dimensions again? (1, **21**, x, y)? Correct @andreazonato

**Comment by andreazonato** [comment] 2021-05-07 13:40
In my opinion, for exp B) FLAG_URB_PARAM=0 and for exp c) FLAG_URB_PARAM=1. And yes, LANDUSEF should always follow num_land_cat, so 21 for exp B)

**Comment by matthiasdemuzere** [comment] 2021-05-07 14:35
@dargueso @andreazonato 

I just created new files, see folder w2w_v3 [here](https://drive.google.com/drive/folders/15QsWRCxFEjZ7fo3C6iP9vqISPr5uw6l1?usp=sharing).

What changes?

**lcz_extent:**

- LANDUSEF: 21 classes, with 1 for the urban
- FLAG_URB_PARAM=0
- NUM_LAND_CAT = 21

**lcz_param:**

- LCZ class numbers from 31 to 41 (included)
- LANDUSEF: 41 classes, with 1's for LCZ classes 
- provide attributes for FRC_URB2D
- URB_PARAM set to float32
- FLAG_URB_PARAM=1
- NUM_LAND_CAT = 41
- Adding a number of other global attributes previously missing ...

I hope this considers all the items mentioned above.

Have a look @dargueso, to see if this also works. If not, then perhaps first try to remove FRC_URB2D? Because as I understand, you got it to work only after removing this? I understand we should keep it in, but at least we could test all other changes ...

**Comment by dargueso** [comment] 2021-05-07 14:58
Thanks, @matthiasdemuzere 

Unfortunately, it still throws an error, even when removing FRC_URB2D. I also tried fixing FieldType that looked like 104L and it's 104 in my file. Also, the global attributes included a few entries that are in @andreazonato's files but are not needed in our case (I believe): FLAG_SANDFRAC, FLAG_IMPERV, FLAG_CLAYFRAC, FLAG_EROD, FLAG_CANFRA  

Other than that, I don't find any differences between your file and mine, so I don't really know why one works and the other doesn't. But I'll still look for differences.

**Comment by dargueso** [comment] 2021-05-07 15:07
Indeed! I've uploaded it there. It's called geo_em.d02.working.nc, not the best naming...

**Comment by dargueso** [comment] 2021-05-07 16:32
@matthiasdemuzere I've taken FRC_URB2D from your file and added to mine, modified FieldType to 104, and metgrid.exe works fine. So the problem must be somewhere else.

I have added this new file to the folder. The name is geo_em.d02.AllFields_working.nc

**Comment by matthiasdemuzere** [comment] 2021-05-07 19:50
ok.

So I fixed the datatype for 104 in FRC_URB2D. That is fine now.

The only major difference I noticed is that LANDUSEF was double instead of float in my version. So this is now also fixed.
I can't image that these few other global attributes would make metgrid crash? So for now I have kept them.

I have uploaded this new file to folder **w2w_v4**. Please have a look. Fingers crossed this works ...

**Comment by matthiasdemuzere** [comment] 2021-05-07 19:58
@andreazonato

While exploring differences between your example file and my own file, I also noticed that the following fields are different (present in yours yet not in mine or vice versa). I am just listing them here, to see later whether these will be an issue or not.

In your dimensions:
	dust_erosion_dimension = 3 ;
	soilcomp = 8 ;

In your variables:

LAKE_DEPTH
IMPERV
CANFRA
EROD
CLAYFRAC
SANDFRAC
FDEPTH
SOILCOMP
SOILCL1F
SOILCL1
SOILCL2F
and a few more SOILCL ... variables.

Yet I assume these are produced by settings flags running WPS to get the default geo_em*.nc file?
Perhaps later we can do a test altering your originel geo_em file, to make sure the w2w tool works also when these dimensions/variables are present ...

**Comment by andreazonato** [comment] 2021-05-09 09:51
@matthiasdemuzere,

These variables arises from a my attempt to run WRF with additional soil information. They are not linked to the urban scheme and they are not used, so of course this is not the source of the problem.

**Comment by dargueso** [comment] 2021-05-09 17:39
@matthiasdemuzere, this new version worked without needing any additional modification, so great news!
I haven't checked the outputs, so I can just confirm it goes through. I will make a sample set of boundary conditions that @andreazonato and me can inspect. You're welcome to have look too, if you want to.

**Comment by matthiasdemuzere** [comment] 2021-05-09 19:00
Yes, that is nice indeed. Great.

I can check the outputs again in more detail tomorrow.
I will then also check the parameter table. I did not manage past Friday due to these annoying datatype errors ...

**Comment by andreazonato** [comment] 2021-05-09 19:12
That's a great result @dargueso ! Wonderful the code worked without any further modification @matthiasdemuzere. Once the wrfinput is ready, please share it with me so I can check if it it ok for running a simulation.

Enjoy the night!

**Comment by dargueso** [comment] 2021-05-09 20:43
metgrid.exe went fine without any modifications, but in order to make the boundary conditions with real.exe, I had to expand LANDUSEF in geo_em.d01.nc so it is consistent with geo_em.d02.nc. They both must have 41 levels (one per land category). I also modified the global attribute  NUM_LAND_CAT to 41 in geo_em.d01.nc, although not sure that is necessary. This tweak must be added to the tool, I guess.
Once done that, the boundary conditions are generated successfully. I will upload a set of sample boundary conditions files in @matthiasdemuzere folder for you to check them out.

**Comment by matthiasdemuzere** [comment] 2021-05-10 09:17
> This tweak must be added to the tool, I guess.

Ha, that is good to know, although I am a bit surprised? So whilst creating boundary conditions for the highest-res domain, also information from the parent domain is still used? Do I understand this correct @dargueso?

I can of course try to add this info to the geo_em.d01.nc file. 

Some questions to make sure I do it right:
- can you add this d01 file to my drive?
- so LANDUSEF should have 41 classes, and classes 31-41 should represent the actual LCZ classes? Would that then be a majority value on this lower resolution @andreazonato? Or is it enough the have the dimensions changed, without having the actual LCZ info?
- I can of course also alter NUM_LAND_CAT to 41.
- None of the other parameters need to be changed?

**Comment by matthiasdemuzere** [comment] 2021-05-10 09:18
> These variables arises from a my attempt to run WRF with additional soil information. They are not linked to the urban scheme and they are not used, so of course this is not the source of the problem.

@andreazonato:

Ok, thanks for clarifying. I will leave these out then.

**Comment by dargueso** [comment] 2021-05-10 09:34
> Ha, that is good to know, although I am a bit surprised? So whilst creating boundary conditions for the highest-res domain, also information from the parent domain is still used? Do I understand this correct @dargueso?

Not exactly. In the namelist, you have to specify  num_land_cat and, AFAIK it only takes one entry. So you need to specify the same for both domains (41). If domain 1 has incorrect land_cat dimension length (21), which is used by LANDUSEF, then it crashes. But I just expanded LANDUSEF from 21 to 41 with zeros.

> I can of course try to add this info to the geo_em.d01.nc file.
> 
> Some questions to make sure I do it right:
> 
> * can you add this d01 file to my drive?

I'll add this d01 file to your GD.

> * so LANDUSEF should have 41 classes, and classes 31-41 should represent the actual LCZ classes? Would that then be a majority value on this lower resolution @andreazonato? Or is it enough the have the dimensions changed, without having the actual LCZ info?

The way I did it: LANDUSEF has length 41 along land_cat dimension, but levels from 21 to 41 are all zeros. domain1 is 10km resolution, so it doesn't make much sense to incorporate city heterogeneity anyway.

> * I can of course also alter NUM_LAND_CAT to 41.
> * None of the other parameters need to be changed?

I didn't need to change any of the other parameters, only dimension cat_land, LANDUSEF, and the global attribute NUM_LAND_CAT.

**Comment by matthiasdemuzere** [comment] 2021-05-10 11:02
@dargueso: perhaps you can add the original d01 also to my drive? So I can touch this one using w2w.

In order to make this generic, one more question.

Is this change required only for the parent domain of the final domain? Or for all parent domains in case there are more nesting steps? Eg. Andrea his sample file was d04, so would this change then be required for d01 to d03?

Have to think a bit how to make this as simple/generic as possible ...

**Comment by andreazonato** [comment] 2021-05-10 11:58
> > This tweak must be added to the tool, I guess.
> 
> Ha, that is good to know, although I am a bit surprised? So whilst creating boundary conditions for the highest-res domain, also information from the parent domain is still used? Do I understand this correct @dargueso?
> 
> I can of course try to add this info to the geo_em.d01.nc file.
> 
> Some questions to make sure I do it right:
> 
> * can you add this d01 file to my drive?
> * so LANDUSEF should have 41 classes, and classes 31-41 should represent the actual LCZ classes? Would that then be a majority value on this lower resolution @andreazonato? Or is it enough the have the dimensions changed, without having the actual LCZ info?
> * I can of course also alter NUM_LAND_CAT to 41.
> * None of the other parameters need to be changed?

As @dargueso said,  the resolution of domain 1) does not require additional information since city heterogeneity is not resolved. Anyway, for all the domains NUM_LAND_CAT should be the same, so it should  be 41 even in the domain 1). For the rest, I think additional modifications are not required in this domain.

**Comment by dargueso** [comment] 2021-05-10 16:07
Just to clarify. We need to change the dimensions of LANDUSEF so the boundary conditions can be created. I also changed the global attribute NUM_LAND_CAT for consistency, but that may not be necessary. I think that even if it isn't necessary, it should be updated to reflect LANDUSEF dimensions.

Yes, we need to modify that in ALL domains. Your approach with a warning is fine.

**Comment by dargueso** [comment] 2021-05-10 16:13
> @dargueso: perhaps you can add the original d01 also to my drive? So I can touch this one using w2w.

I've uploaded the original geo_em.d01.nc file to your GD.

**Comment by dargueso** [comment] 2021-05-19 14:04
@matthiasdemuzere I have checked the file and, as far as I can tell, it is the same as I generated.

**Comment by matthiasdemuzere** [comment] 2021-05-19 14:05
Ok, great. So then this is fine!

**Closed** 2021-05-24 18:39 UTC
