### ISSUE TITLE
first version w2w and output available

### ISSUE THREAD

**Issue by matthiasdemuzere** [matthiasdemuzere/wrf-lcz-KL#6] opened 2021-04-22 13:31 UTC
@dargueso @andreazonato 

The past few days I have spent quite a bit of time on this, and I now created a first version of the w2w python module. Have a look at the repository, and the cleaned up repo. Feel free to try out the module yourself.

Resulting files are unfortunately too big to be part of the repo, you can find them [here](https://drive.google.com/drive/folders/18-JpRLhLdhVIXaE0QLw5sAHN4qHXBK4K?usp=sharing).

I have tried to be as precise as possible, but bugs might still occur.
So it could be great if both of you could have a look into the resulting .nc files and code?

@andreazonato: could you specifically have a look at the *LCZ_params.nc file, to see whether all information is there and has the right format? 

I was thinking: should I derive the same file for your Bologna domain, to see whether it works? We could compare it then with the file you obtained following the more default pre-processing?

In that case I would need your default geo_em*nc file and LCZ map. For the latter, I could also crop the domain out of my European map ...

**Comment by dargueso** [comment] 2021-04-22 13:38
Great @matthiasdemuzere! Thanks!
I'll give it a look tomorrow and try it myself. I'll let you know how it goes.

**Comment by andreazonato** [comment] 2021-04-22 13:50
I had a quick look, and it seems perfect! 

The z location of URB_PARAMS are ok, and values are reasonable, so that's great.

I'm only wondering why mean building height (92) and area weighted mean building height (94) are so different between them.

How did you calculate the area weighted mean building height (94)?

**Comment by matthiasdemuzere** [comment] 2021-04-22 14:00
> Great @matthiasdemuzere! Thanks!
> I'll give it a look tomorrow and try it myself. I'll let you know how it goes.

Thanks @dargueso: at least the *NoUrban*nc file should the same as yours, as I used your script in my routine ...

**Comment by matthiasdemuzere** [comment] 2021-04-22 14:02
> How did you calculate the area weighted mean building height (94)?

Thanks for checking @andreazonato. 

I calculated HGT_URB2D = MH_URB2D * BLDFR_URB2D

See code [here](https://github.com/matthiasdemuzere/wrf-lcz-KL/blob/2a5d69230fcc81f348efc366fca550d1b632d2ab/w2w.py#L313).

Is this not the right way to do it?

**Comment by andreazonato** [comment] 2021-04-22 14:12
> > How did you calculate the area weighted mean building height (94)?
> 
> Thanks for checking @andreazonato.
> 
> I calculated HGT_URB2D = MH_URB2D * BLDFR_URB2D
> 
> See code [here](https://github.com/matthiasdemuzere/wrf-lcz-KL/blob/2a5d69230fcc81f348efc366fca550d1b632d2ab/w2w.py#L313).
> 
> Is this not the right way to do it?

No, it should be simply a mean height, but weighted using the area of the roof of each building.

Let's make an example:

LCZA: building width BWA=5; mean building height HA=20;
LCZB: buiding width  BWB=10; mean building height HB=10;

so the aggregate HGT_URB2D, in that cell, assuming there is 1 LCZA and 1 LCZB is:

HGT_URB2D= (BWA^2*HA+BWB^2*HB)/(BWA^2+BWB^2)=12.

while

MH_URB2D= (HA+HB)/2=15

**Comment by matthiasdemuzere** [comment] 2021-04-23 12:10
@andreazonato: thanks for explaining the HGT_URB2D calculation. Now I understand.

I implemented this, see [here](https://github.com/matthiasdemuzere/wrf-lcz-KL/blob/1d0ddb8197db3f9254a028a5178e249578ceff51/w2w.py#L393).

I also updated the files in Google Drive. I believe this looks much better, please have a look ...

**Comment by andreazonato** [comment] 2021-04-23 12:19
Yes, now it seems ok, great job!

Once you (or Daniel) will run this simulation, please make the variables:

LP_URB2D
LB_URB2D
HGT_URB2D
MH_URB2D
STDH_URB2D
LF_URB2D

printable, adding in the Registry.EM_COMMON the letter "h" after i0, so we can be sure those values are at the correct nz row.

**Comment by matthiasdemuzere** [comment] 2021-04-23 12:25
If both of you accept these inputs, I believe indeed we can proceed with exp. B and C.

Perhaps @andreazonato can talk to @dargueso about all required settings / flags, to make WRF run with SLUCM **and** LCZ information?

And then I guess we just have to wait?

Personally I'd like to use this *wait* time to focus on other projects.

Once results are there, I suggest the following workflow:
- analyze results (to be decided who takes the lead)
- depending on results, reflect about (peer-review) publication
- clean up w2w.py routine, add things if needed (see ideas on To Do of README) 
- make all available to the public

**Comment by andreazonato** [comment] 2021-04-23 15:41
Yes, I'll wait to interact with @dargueso  about the simulations.


Regarding: > * clean up w2w.py routine, add things if needed (see ideas on To Do of README):

I would add all the parameters required for all the urban schemes, so it it a more general code.

The only thing missing is: **Distribution of Building Heights (HI_URB2D) 118-132**

How is this calculated? Showing you an example, as before:

LCZ_A= 20% of buildings are 5 m, 80% of buildings are 10 m.
LCZ_B= 30% of buildings are 5 m, 70% of buildings are 20 m.

For the aggregation process, assuming that a WRF cell has 1 LCZ_A and 1 LCZ_B, the new distribution will be:

Buildings below 5 m:
HI_URB2D(:,118,:)=(20%+30%)/2= 25%

Buildings below 10 m:
HI_URB2D(:,119,:)=(80%)/2= 40%

Buildings below 15 m:
HI_URB2D(:,120,:)=0%

Buildings below 20 m:
HI_URB2D(:,121,:)=70%/2=30%.

With of course, a sum that is 100%
And so on until HI_URB2D(:,132,:) (for small and lower cities, of course, the values over 40 m will be all 0).


That should cover all the spectrum of possible urban schemes in WRF.


Andrea

**Comment by dargueso** [comment] 2021-04-23 16:10
Hi, I've run the python code and it runs smoothly in a fresh python environment. I just had to install a few modules. So this is perfect!
I've noticed that GREENFRAC is exactly the same in both geo_em.d02_NoUrban.nc and geo_em.d02.nc. This is because in my script original script, the part where GREENFRAC is modified was commented. Unfortunately, I didn't uncommented it and experiment A is running with the original GREENFRAC. For consistency and given that the simulations past half way, we cannot change it now, but it something that should be changed for the tool we will make available. Hope that doesn't make a significant effect. I will check the model outputs to see if I can detect a signal in near-surface variables (temperature and humidity).

All the rest looks fine to me. I can't really say much about exp C geo_em file, where all the LCZ parameters are specified, but it looks like @andreazonato has already commented on those.

I will start generating boundary conditions for experiment b and launch the simulations. Once they're running, I can start with exp C and will appreciate your input, @andreazonato.

**Comment by matthiasdemuzere** [comment] 2021-04-26 08:10
> How is this calculated? Showing you an example, as before:
> 
> LCZ_A= 20% of buildings are 5 m, 80% of buildings are 10 m.
> LCZ_B= 30% of buildings are 5 m, 70% of buildings are 20 m.

@andreazonato:

Ok, I can try to implement this as well. 

But: how do you decide what the building height distribution is within one LCZ?
Eg. 

For LCZ 2, we work with an average height of 15m, and a standard deviation of 3m. Yet how do you translate this to eg. x% below 5m, y% below 10m, etc ...?

**Comment by matthiasdemuzere** [comment] 2021-04-26 08:29
> I've run the python code and it runs smoothly in a fresh python environment. I just had to install a few modules. So this is perfect!

@dargueso this is good to know. What modules did you have to add? Then I can add this to the w2w.yml file ...

**Comment by andreazonato** [comment] 2021-04-26 09:07
> > How is this calculated? Showing you an example, as before:
> > LCZ_A= 20% of buildings are 5 m, 80% of buildings are 10 m.
> > LCZ_B= 30% of buildings are 5 m, 70% of buildings are 20 m.
> 
> @andreazonato:
> 
> Ok, I can try to implement this as well.
> 
> But: how do you decide what the building height distribution is within one LCZ?
> Eg.
> 
> For LCZ 2, we work with an average height of 15m, and a standard deviation of 3m. Yet how do you translate this to eg. x% below 5m, y% below 10m, etc ...?

Good Question. It can be done for example with a gaussian (assuming a standard deviation at least of 5 m). In this case, we will have 70% of 15 m , 15 % of 10 m and 20 % of 20 m. That's actually up to the user, and strongly depend on the city involved

**Comment by matthiasdemuzere** [comment] 2021-04-26 09:13
> In this case, we will have 70% of 15 m , 15 % of 10 m and 20 % of 20 m

I assume you mean 15% of 20m?

> That's actually up to the user, and strongly depend on the city involved

Of course. But as I have mentioned before: in my opinion LCZ info should serve as a first proxy to describe the urban landscape, especially useful for areas that lacks other datasets. In case more detailed datasets are available (so detailed that example building height density can be derived from it), then I no longer see the added value of LCZs ...

I'll think a bit more on how to include these % values ....

**Comment by andreazonato** [comment] 2021-04-26 09:23
> I assume you mean 15% of 20m?

Yes, Sorry, my mistake.


> Of course. But as I have mentioned before: in my opinion LCZ info should serve as a first proxy to describe the urban >landscape, especially useful for areas that lacks other datasets. In case more detailed datasets are available (so detailed that > example building height density can be derived from it), then I no longer see the added value of LCZs ...

I agree with you about this philosophy. The only boundary in my opinion, is that it should lay in the gap of Stewart & Oke 2012

**Comment by matthiasdemuzere** [comment] 2021-04-26 10:38
> The only boundary in my opinion, is that it should lay in the gap of Stewart & Oke 2012

@andreazonato 

Indeed. So my suggestion is to work with a bounded normal distribution framework, that allows us to make a distribution using min, max, mean and std.

See example below for LCZ 2 (Taking values from S02012 and Stewart 2014):

# LCZ 2
min_val = 10
max_val = 25
mean = 15
std = 3

![image](https://user-images.githubusercontent.com/6926916/116069299-83648500-a68b-11eb-8698-d378b082e771.png)

And then count the number of entries between the pre-defined height bounds for HI_URB2D.

Just a last question @andreazonato:

HI takes indices between 118-132. So:
118 = [ 0 - 5m ]
119 = [ 5 - 10m ]
....
132 = [70 - 75m ]

Correct?

If so, this could also provide the framework for the maximum height of LCZ 1, which is undefined in SO2012. 75m is low for CBDs in large cities, but at least it will be consistent? 

Or is the last one more of an upper open bound:
132 = [ > 70m ]

?

Once this is clear, I can try to implement this into the code ...

**Comment by dargueso** [comment] 2021-04-26 10:45
@matthiasdemuzere using the environment file you provide it all went fine. Nothing to add to the yml file.

**Comment by andreazonato** [comment] 2021-04-26 10:48
> HI takes indices between 118-132. So:
> 118 = [ 0 - 5m ]
> 119 = [ 5 - 10m ]
> ....
> 132 = [70 - 75m ]

> Correct?

> If so, this could also provide the framework for the maximum height of LCZ 1, which is undefined in SO2012. 75m is low for > CBDs in large cities, but at least it will be consistent?

Yes, that' correct in this way. So that means that bep+bem does not contemplate buildings higher than 75 m. And as you suggest, large cities have higher buildings. In my opinion, avoiding to consider buildings higher than 75 m does not make too much difference during the simulations: they are few, and their lambda_p is really low. 


Anyway, I'll write Alberto Martilli asking him about this issue

**Comment by matthiasdemuzere** [comment] 2021-04-26 13:41
@andreazonato 

> With of course, a sum that is 100%

I have implemented this routine now, but upon inspection, I have noticed that the sum across index 118 to 132 often does not add up to 100%. Which in my opinion makes sense, as the aggregation is done over 10 x 10 pixels, many of which - especially around the edges of the urban center - will have no buildings, and thus, the aggregation will very often result in values < 100%.

This made me check the difference between FRC_URB2D (left panel) and LU_index between 30 and 41 (right panel), see figure below.
 
![image](https://user-images.githubusercontent.com/6926916/116090075-c7fc1a80-a6a3-11eb-93b4-2f265e9be4ea.png)

The Urban extent in FRC_URB2D is much larger, because it is obtained via assigning urban fraction to LCZ classes in high-res, and afterwards being aggregated. LU_index on the contrary, depicts the majority filter values ...

So my question here is: what should be used as the baseline urban extent descriptor?

If LU_INDEX, I could set the urban parameters for all pixels that have LU_index not in [30-41] to 0. As such, all fields will be consistent in extent, and follow the information in LU_index.

This helps to sum extent for HI, as you can see from the plot where HI is summed over all indices (118-132), and masked by LU_INDEX. Yet there are still pixels at the edges with values < 100%. This could then still be solved by scaling these values to 100%, whilst keeping their internal height distribution.

Eg., for an urban pixel:
- no scaling:    [ 2.  , 28. ,   0. ,  0. ,  0. ,  0. ,  0.1,  1.3,  8.3, 21. , 21. ,  8.3,  1.3,  0.1,  0. ], sum = 91.4%
- after scaling: [ 2.2, 30.6,  0. ,  0. ,  0. ,  0. ,  0.1,  1.4,  9.1, 23. , 23. ,  9.1,  1.4,  0.1,  0. ]  , sum = 100%

![image](https://user-images.githubusercontent.com/6926916/116090895-a2234580-a6a4-11eb-9fcf-4588c4e21254.png)

What do you think?

**Comment by andreazonato** [comment] 2021-04-26 14:02
Those are great observations.

In my paper, I did the scaling, in order to have always 100% of Height histograms. As you pointed out, it is even a feedback for a good aggregation. So in my opinion, the scaling is the best method to calculate the height histograms (HI_URB2D).


The issue about the urban extent indicator is really delicate, and we should put a lot of attention to it.

What I did in my paper, is the following.

For the case without aggregation (i.e. with simply majority values and look-up table), I took obviously the majority values. That means, if the pixel has 49% of LCZ cells, that's of course rural.

Different is the case with aggregation: I put a threshold of 0.2 for FRC_URB2D (that is then my urban extent indicator), and even if the majority value of the pixel is rural, the cell is urban (taking the majority value). This is not an issue for the calculation of the fluxes, since the land-surface scheme subsequently makes a weighted average, and then if we have 80% of the pixel that is rurall, the component of the urban part is just the 20%.


In my opinion, we should proceed in the same way. What do you think?

**Comment by dargueso** [comment] 2021-04-26 14:42
LU_INDEX has preference over FRC_URB2D in the code, so the model first checks LU_INDEX to trigger the Urban Canopy Model. If LU_INDEX is not an urban category, it won't care about the urban fraction. Another question is whether you want to keep it clean to avoid any confusing by the user, but is not a problem for the model.

**Comment by matthiasdemuzere** [comment] 2021-04-26 14:46
Ha, ok. This is good to know.

Then I'd prefer to set FRC_URB2D == 0, where LU_INDEX not in [ 30 - 41], so that users are not confused in case they check the underlying fields ... 

Perhaps I can try to have this feature with a flag (on by default), so that one could still get the original values if wanted ....

**Comment by andreazonato** [comment] 2021-04-26 15:00
> Or did I miss something?
> Don't you think it is more clean to set FRC_URB2D == 0, where LU_INDEX not in [ 30 - 41]?

Actually, the point is that if you put FRC_URB==0 where there are no LCZs (through the majority value), you will loose all the advantages of the aggregation method in the boundaries of the city. In my opinion, it would be better first to calculate the FRC_URB2D (accounting for both the UCZ/(total LCZ) ratio and the fraction of each UCZ), and then put a threshold on the FRC_URB2D. Once FRC_URB2D is relevant (a value that allows a substantial influence of the urban landuse), LCZ should be calculated as the majority of JUST THE URBAN PIXELS and not of all the pixels. In this way, we have even the information of urban areas where UCZs does not overcome the rural areas.

**Comment by matthiasdemuzere** [comment] 2021-04-26 15:22
mmm ... 

As I see it, both have trade-offs.

From an aggregated pixel resolution point of view:
- I believe the FRC_URB2D values are correct, presenting the average impervious area for a pixel. 
- the LCZ majority setting is more complex:
       1. Neglecting natural LCZs when taking the majority will artificially increase the urban extent, as you can have a grid cell with 70% LCZ A (forest), 10% LCZ 2 and 20% LCZ 6, and then this grid cell would be LCZ 6 after filtering? However, the FRC_URB values for this pixel would however be more correct, having a value of  (0.7 * 0) + (0.1 * 0.9)  + (0.2 * 0.6) = 0.21. 
       2. The opposite is of course true when considering natural areas in the LCZ majority filtering. Then we clearly suppress the urban extent, especially at the boundaries of the urban areas, as indicated by @andreazonato above.

So:
- if a pixel is only considered urban when LU_INDEX in [30 - 41], **AND**
- FRC_URB2D is used to indicate the urban fraction of these pixels (and not assigned via the lookup table, as this would be lead to a value of 0.6  - as majority is LCZ 6 - in the example above) 

Then I agree we could neglect the natural LCZs when doing the LCZ majority filtering.
That means that it is really FRC_URB2D which is key (an not the LCZ majority value), as FRC_URB2D defines all the urban - rural partitioning and calculation within the LSM ...

Do you all agree?

PS. I am not sure why you refer to UCZ here? I do not use this concept for FRC_URB2D, as I 
assign FRC_URB2D to LCZs in high-res, and then aggregate? So I am not sure what you mean by: 
> In my opinion, it would be better first to calculate the FRC_URB2D (accounting for both the UCZ/(total LCZ) ratio and the fraction of each UCZ)

**Comment by andreazonato** [comment] 2021-04-26 15:31
<if a pixel is only considered urban when LU_INDEX in [30 - 41], AND...
Do you mean using the majority value?

> Do you all agree?
I think FRC_URB2D (calculated considering even The rural LCZ) should be the indicator of the urban extent. It does not matter if a pixel is URBAN [30 -41] even if the FRC_URB2D is 0.3. In this case, the rural part is treated separately in the land-surface scheme, while the urban part (even if not the majority) by the urban scheme. That's one of the advantages of using the  aggregation process. Of course, I would consider rural pixels with FRC_URB2D<0.
2, let's say, since their contribute is not so relevant.


> PS. I am not sure why you refer to UCZ here? I do not use this concept for FRC_URB2D, as I
>assign FRC_URB2D to LCZs in high-res, and then aggregate? So I am not sure what you mean by:
>In my opinion, it would be better first to calculate the FRC_URB2D (accounting for both the UCZ/(total LCZ) ratio and the >fraction of each UCZ)

UCZ is a LCZ from 1 to 11 (Urban), while LCZ is all, including the rural part. 
I mean that, if in a pixel there is 50% of LCZ 6 (0.6 of urban fraction) and 50% of forest, the urban fraction will be 
(0.6 + 0)/2=0.3

**Comment by matthiasdemuzere** [comment] 2021-04-26 18:50
> Do you mean, using the majority value?

Yes.

> Of course, I would consider rural pixels with FRC_URB2D<0.2, let's say, since their contribute is not so relevant.

In a way, this 0.2 threshold is rather arbitrary, no? Can't we just keep all FRC_URB, so the full range between 0 and 1?

> UCZ

Ha, ... ok. Now I understand. Note that only LCZs 1-9 refer to the UCZs defined by Oke in 2004 (just a detail).

![image](https://user-images.githubusercontent.com/6926916/116135165-11af2a00-a6d1-11eb-8d04-537b2910b39a.png)

**Comment by matthiasdemuzere** [comment] 2021-04-26 18:51
But from all the above, I think it is clear what needs to be done ... arrghh .. and I thought I was almost there ... not yet.

**Comment by andreazonato** [comment] 2021-04-27 08:56
> In a way, this 0.2 threshold is rather arbitrary, no? Can't we just keep all FRC_URB, so the full range between 0 and 1?

Yes, the value is arbitrary. And now I try to explain you why we cannot keep the full range. The issue is really delicate, as you noticed.

Let's say we have a pixel with 0.01 of FRC_URB2D, LCZ 2. The rest (99.99) is vegetation, let's say croplands.
So, since here there is a bit of urban surface, and LU_INDEX=32, WRF will treat it as urban: it will call the urban scheme for the 0.01, and the land-surface scheme for the 99.99. However, the vegetation part here is assumed to be urban vegetation, (decided into a lookup-table), let's say we set it as forest. Hence, WRF will treat our cell as 0.01 URBAN, and 99.99 as FOREST, that is not correct, since it should be croplands. For this reason  I put a threshold at 0.2, so we avoid to treat all the cells with really few urban cover with a wrong vegetation class.


I can think even to hardcode WRF, to avoid this issue. Let me think about this.

**Comment by andreazonato** [comment] 2021-04-27 12:08
Ok, I got to a conclusion, that will cost us really low effort in terms of coding.

I would create a new field into the WPS, lets call it LU_INDEX_NOURBAN. It takes the values of whatever database for the vegetation landuse. I will make it read by WRF in the initialization process, and I'll assign to the cells with FRC_URB2D>0 this value. In case these cells are URBAN even for the not-LCZ database, in this case, it will be urban vegetation. In this way, we can keep all cells with FRC_URB2D=[0,1] and assign to them the majority value of LCZ,  avoiding to account the rural pixels in the computation.

What do you think about it?

**Comment by matthiasdemuzere** [comment] 2021-04-27 12:40
Thanks for your thoughts @andreazonato.

To be honest, I am a bit reluctant to change anything into WRF or WPS. I mean, our idea was to simplify the original WUDAPT-to-WRF package, but this seems to go way beyond this.

As I see it, WRF should not treat vegetation as urban vegetation (forests??) whenever FRC_URB2D > 0. It should treat it as an independent natural fraction that can have different vegetation types as well. Yet this is work to be done by others in the community, and not as part of what we try to do here?

So perhaps we can keep working with your 0.2 threshold for now (can be a parameter in the script°, and make sure the underlying reasoning is clearly described if we manage to write all of this as a paper or preprint.

What do you think?

**Comment by matthiasdemuzere** [comment] 2021-04-27 13:52
Ok, so based on the discussion above, I'll suggest to do the following.

- For the urban extent, with LU_INDEX = 13, and to be used in Exp. B.

1. Mask the natural LCZs
2. Perform majority filtering
3. Put urban LCZs as 13 in LU_INDEX

- For Exp. C, integrating all other LCZ information

1. Same as for Exp. B, but now put LCZ classes in LU_INDEX, as 30 to 41.
2. Obtain FRC_URB by aggregation of high-res FRC_URB, set values > 0.2 to 0 (use parameter flag for this)
3. Produce all other URB_PARAM fields, and make sure their extent does not exceed the FRC_URB extent.

I hope this summarizes all of the above well? If not, please let me know @andreazonato ...

**Comment by andreazonato** [comment] 2021-04-27 14:06
> Ok, so based on the discussion above, I'll suggest to do the following.
> 
> * For the urban extent, with LU_INDEX = 13, and to be used in Exp. B.
> 
> 1. Mask the natural LCZs
> 2. Perform majority filtering
> 3. Put urban LCZs as 13 in LU_INDEX
> 
> * For Exp. C, integrating all other LCZ information
> 
> 1. Same as for Exp. B, but now put LCZ classes in LU_INDEX, as 30 to 41.
> 2. Obtain FRC_URB by aggregation of high-res FRC_URB, set values > 0.2 to 0 (use parameter flag for this)
> 3. Produce all other URB_PARAM fields, and make sure their extent does not exceed the FRC_URB extent.
> 
> I hope this summarizes all of the above well? If not, To be honest, I am a bit reluctant to change anything into WRF or WPS. I mean, our idea was to simplify the original WUDAPT-to-WRF package, but this seems to go way beyond this.please let me know @andreazonato ...

Yes, I agree with you about this scheme.

Regarding the new field:
> To be honest, I am a bit reluctant to change anything into WRF or WPS. I mean, our idea was to simplify the original WUDAPT-to-WRF package, but this seems to go way beyond this.

I'm trying to make this thing as simple as possible. We can proceed with the threshold of FRC_URB2D>0.2, and then we can try with an additional field  in order to use all the FRC_URB2D (0 to 1). If we notice substantial differences we can proceed implementing the addittional field, if not we can keep with the threshold.


Do you agree?

**Comment by matthiasdemuzere** [comment] 2021-04-27 15:16
Here is a comparison between LU_INDEX = 13, derived from:
- left: majority LCZ WITHOUT masking natural LCZs beforehand
- right: majority LCZ WITH masking natural LCZs beforehand

The difference is huge. About ~4x more pixels are urban in the latter case.

For now I will continue along this track, as I understood FRC_URB is the decisive parameter to say what is urban and what is not, no? @andreazonato? Or should I derive the urban extent for Exp. B directly from FRC_URB > 0.2? But then this field will not match the LU_INDEX [30 - 41] extent anymore? 

I have the feeling I / we are going in circles here ....

![image](https://user-images.githubusercontent.com/6926916/116261807-4c1fd200-a778-11eb-9e97-0bdeb55afa37.png)

**Comment by dargueso** [comment] 2021-04-27 15:33
Hi guys, 
I'm sorry I have slightly stepped aside in this discussion, but I don't have much to add. Most of the choices seem to be compromises and I understand the various options are valid, but I don't really have a strong reason to argue for one or the other, so I leave it you guys. 

I do feel that the right hand side map shows a too large number of urban pixels, but I can't say which one is closer to reality from a broad perspective. That is, are all those urban pixels in the latter plot anything close to an urban landscape?

**Comment by andreazonato** [comment] 2021-04-28 09:18
Hi guys...

>I have the feeling I / we are going in circles here ....
Yeah, that's true. Merging LCZ with WRF is really complicated and we have to find compromises...

In my opinion. for the exp. B), LCZ should be calculated with the majority values INCLUDING the rural areas. That's the standard way, and with exp C) we want to demonstrate that the aggregation method works better.

Regarding the exp C):

I would use the threshold FRC_URB2D>0.2 first. That means: calculating the FRC_URB2D, using  it as a mask for the LCZ extent and for the URB_PARAM matrix.

Moreover, I implemented in WRF a new LANDUSE, which does NOT include the LCZ, in order to use the vegetation that there should be in areas with low FRC_URB2D. So we could split exp C) in 2 different experiments:

C1) Threshold on FRC_URB2D>0.2 ----> Urban areas are considered if FRC_URB2D>0.2, with a single urban vegetation category
C2) NO Threshold of FRC_URB2D  ----> We consider all LCZ, even if FRC_URB2D is really small. Here vegetation is taken from another landuse, that is the one without LCZ.

Then we can conduct a sensibility test, in order to evaluate the differences between C1) and C2). In my opinion  there will be really few differences, and this hypothesis can reinforce the fact that we put a threshold on FRC_URB2D.


What do you think?


Andrea

**Comment by matthiasdemuzere** [comment] 2021-04-28 09:48
> In my opinion. for the exp. B), LCZ should be calculated with the majority values INCLUDING the rural areas. That's the standard way, and with exp C) we want to demonstrate that the aggregation method works better.

I disagree. The goal of C. is to look into the added values of the intra-urban heterogeneity, only. As such, the urban extent covered by urban areas should be the same in Exp. B. and C.

I keep working on what I do now:
1. FRC_URB is obtained via aggregation
2. Filtered for values < 0
3. Remaining pixels with FRC_URB > 0 (so 0.2 in our case) are used to define the urban extent
4. LCZ is majority filtered with masked natural areas, and LCZ values are only retained where FRC_URB > 0, so these 2 fields are consistent.


> 
> Regarding the exp C):
> 
> I would use the threshold FRC_URB2D>0.2 first. That means: calculating the FRC_URB2D, using it as a mask for the LCZ extent and for the URB_PARAM matrix.

Indeed, this is what I do no. I introduced a parameter FRC_THRESHOLD, so one is flexible on the value used here.

> Moreover, I implemented in WRF a new LANDUSE, which does NOT include the LCZ, in order to use the vegetation that there should be in areas with low FRC_URB2D. So we could split exp C) in 2 different experiments:
> 
> C1) Threshold on FRC_URB2D>0.2 ----> Urban areas are considered if FRC_URB2D>0.2, with a single urban vegetation category
> C2) NO Threshold of FRC_URB2D ----> We consider all LCZ, even if FRC_URB2D is really small. Here vegetation is taken from another landuse, that is the one without LCZ.
> 
> Then we can conduct a sensibility test, in order to evaluate the differences between C1) and C2). In my opinion there will be really few differences, and this hypothesis can reinforce the fact that we put a threshold on FRC_URB2D.


I am not sure about the above. As mentioned before, I think these adjustments go well beyond the goal of our work. As I assume this requires the user to change something manually in the WRF code? This is exactly the type of things that should be avoided. If we find this is a limitation of WRF, we should inform the main developers about this, and get it into an official release?

Also, such an experiment would require us to do a fourth run, something we initially did not forsee? What do you think about this @dargueso?

In case we do want to consider this, from the above it is also not clear to me how this will affect my code development ....

**Comment by andreazonato** [comment] 2021-04-28 10:03
>I am not sure about the above. As mentioned before, I think these adjustments go well beyond the goal of our work. As I >assume this requires the user to change something manually in the WRF code? This is exactly the type of things that should be >avoided. If we find this is a limitation of WRF, we should inform the main developers about this, and get it into an official release?

>Also, such an experiment would require us to do a fourth run, something we initially did not forsee? What do you think about >this @dargueso?

>In case we do want to consider this, from the above it is also not clear to me how this will affect my code development ....

Yes, this is something that requires a little modification to the WRF code. I actually wanted to take advantage of this work, to test the modification i just did, but if it goes beyond the goal of this work, it does not matter.  

> we should inform the main developers about this, and get it into an official release?
Actually the main developer of these modifications, it's me, so for this reason I'm pushing in this direction to try this new modification, in order to put this in a future release.

Anyway, it does not matter, if it goes behyond the effort that should be put in this project.

>I disagree. The goal of C. is to look into the added values of the intra-urban heterogeneity, only. As such, the urban extent >covered by urban areas should be the same in Exp. B. and C.
 OK, now it is more clear. I was not 100% about the differences in the urban extent. Thank you

**Comment by matthiasdemuzere** [comment] 2021-04-28 10:10
Ok, let's see what @dargueso has to say about an additional simulation. If ok, we can discuss further would should be addressed in my code developments as well ...

But for now, I'd like to get the basis for Exp. B and C done. I am spending way much more time on this as I originally thought / have available ....

**Comment by dargueso** [comment] 2021-04-28 13:46
Hi, 

In my opinion, the priority should be getting all 3 original experiments done, with the goal of understanding the impact of urban heterogeneity on precipitation. 

Since this idea stems partly from the experiments we did for Li et al. 2020 GRL, it'll be nice to make them as similar as possible to those. We should also remember that we are not going to perform any model evaluation (we don't have the observational data), so we will hinge on those results to argue that the model is performing well.

I think this goal can be pursued using @matthiasdemuzere approach:

> > I keep working on what I do now:
> 
> FRC_URB is obtained via aggregation
> Filtered for values < 0.2
> Remaining pixels with FRC_URB > 0 (so 0.2 in our case) are used to define the urban extent
> LCZ is majority filtered with masked natural areas, and LCZ values are only retained where FRC_URB > 0, so these 2 fields are consistent.

All the rest, including the tool, is great, but perhaps not a priority. Given that we are doing all this work, I feel it is neat to share it with others, but I don't think we should entirely design our experiments based on the tool we want to share, which requires to be more generic than our experiments. For our experiments we can make assumptions ad hoc, and they will still be correct.

So, I think we should define an area that we consider urban (FRC_URB > 0.2 sounds reasonable) and define LCZ within that area for experiment C. Exp B and C should have the exact same urban extension, no matter how that is defined or the model subtleties. All assumptions and choices can be set as options in the tool, and document why they were made. If the user wants to change it, we give them the option. Although it looks like it should be done at some point in the future, I wouldn't add changes to WRF or WPS for these particular experiments. Firstly because we want to make them comparable to what was done before (Li et al. 2020) and coherent with Exp A. And secondly, because it goes beyond the original goal of the project. 

As for making additional experiments, we will have to ask for additional resources in the next round. I asked for quite a lot of resources this round, combining two projects. I am afraid that I will already have to sacrifice experiments planned as part of the other project in order to complete Exp B and C, so I don't feel like rolling this over to the next period. Also, that would extend this project  a few more months, which is not ideal. 

Cheers!

**Comment by matthiasdemuzere** [comment] 2021-04-28 14:21
Hi @dargueso,

Thanks for your reflection. I did not realize this side-project would consume CPU time from another project. Hopefully not too much.

But I agree.  Let's get this done, and see where the results lead us. 
On the evaluation: if results look intriguing, but could try to see what we get out of the [GPM IMERG rainfall product (0.1x0.1° spatial resolution, available half-hourly)](https://disc.gsfc.nasa.gov/datasets/GPM_3IMERGHH_06/summary?keywords=%22IMERG%20final%22). To be seen.

Finally, I do think the current shape of the tool is already a good step forward. That is of course, if the produced results with the second version (see #11) are fine.

**Comment by dargueso** [comment] 2021-04-28 14:50
Hi @matthiasdemuzere, 
Oh, no, don't take me wrong. I made the decision to merge them to reduce the workload when applying for CPU time and also my estimations turned out to be a bit optimistic! Nothing to worry about, just a matter of prioritising :)
I'll check the outputs with the tool tomorrow morning, and will let you know.

**Closed** 2021-05-24 18:39 UTC
